### ISSUE TITLE
Rename project moodle-docker-compose?

### ISSUE THREAD

**Issue by danpoltawski** [danpoltawski/docker-moodle#16]
Perhaps naming this project moodle-docker-compose would be more intuitive? Any other suggestions welcome, but docker-moodle is not really right for me.

**Comment by scara** [comment]
Wondering if we could stick with the current name ([at least](https://github.com/moby/moby/issues/26556), rename it to `moodle-docker`) and removing the related projects by including those images building - i.e. `build: path/to/image` instead of `image: public-image-name` - in this "compose".

HTH,
Matteo

**Comment by danpoltawski** [comment]
I had the images in this project to start with, but I much prefer them to be seperate images/projects as I think they exist separately quite well

**Comment by stronk7** [comment]
moodle-xxxx is well aligned with other [moodlehq](https://github.com/moodlehq) projects, so +1 to for that (esp assuming this could end, some day, moved there).

And surely moodle-docker is enough, at least I see the "compose" part of it not needed. I don't mind much.

**Comment by Dagefoerde** [comment]
`docker-moodle` is not a good idea either way, because https://www.andreas-jung.com/contents/dont-use-docker-in-github-repo-names-or-as-twitter-handle.
I am all for `moodle-docker`!

**Comment by danpoltawski** [comment]
Have completed the rename to moodle-docker, thanks for the comments
